import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Covers are procedurally generated SVG served from a route handler, and
      // event imagery is arbitrary remote URLs in production. next/image adds
      // an optimisation pipeline neither case benefits from.
      '@next/next/no-img-element': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // `next-env.d.ts` is generated by the framework and is not checked in.
    ignores: ['.next/**', 'node_modules/**', 'drizzle/**', 'docs/**', 'next-env.d.ts'],
  },
];

export default config;
